export const enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  BOOK_CATEGORY_NAME_ALREADY_EXISTS = 'BOOK_CATEGORY_NAME_ALREADY_EXISTS',
  CANNOT_DELETE_BOOKS_EXIST = 'CANNOT_DELETE_BOOKS_EXIST',
  INVALID_BOOK_CATEGORY = 'INVALID_BOOK_CATEGORY',
  INVALID_BOOK_PUBLISHER = 'INVALID_BOOK_PUBLISHER',
  INVALID_PRINTING_OFFICE = 'INVALID_PRINTING_OFFICE',
  CANNOT_DELETE_BOOK_ISSUED = 'CANNOT_DELETE_BOOK_ISSUED',
}
